/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.api;

import com.github.opensibyl.client.model.Sibyl2ClazzWithPath;
import com.github.opensibyl.client.model.Sibyl2FunctionContext;
import com.github.opensibyl.client.ApiException;
import com.github.opensibyl.client.model.ObjectFunctionWithSignature;
import com.github.opensibyl.client.model.Sibyl2ClazzWithPath;
import com.github.opensibyl.client.model.Sibyl2FunctionContext;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MainApi
 */
@Disabled
public class MainApiTest {

    private final MainApi api = new MainApi();

    /**
     * class query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ClazzGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String _file = null;
        List<Sibyl2ClazzWithPath> response = api.apiV1ClazzGet(repo, rev, _file);
        // TODO: test validations
    }

    /**
     * func query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String _file = null;
        String lines = null;
        List<ObjectFunctionWithSignature> response = api.apiV1FuncGet(repo, rev, _file, lines);
        // TODO: test validations
    }

    /**
     * func ctx query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncctxGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String _file = null;
        String lines = null;
        List<Sibyl2FunctionContext> response = api.apiV1FuncctxGet(repo, rev, _file, lines);
        // TODO: test validations
    }

}
