/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.api;

import com.github.opensibyl.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for OpsApi
 */
@Disabled
public class OpsApiTest {

    private final com.github.opensibyl.client.api.OpsApi api = new OpsApi();

    /**
     * upload status query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void opsMonitorUploadGetTest() throws ApiException {
        api.opsMonitorUploadGet();
        // TODO: test validations
    }

    /**
     * ping example
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void opsPingGetTest() throws ApiException {
        api.opsPingGet();
        // TODO: test validations
    }

    /**
     * sibyl version
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void opsVersionGetTest() throws ApiException {
        api.opsVersionGet();
        // TODO: test validations
    }

}
