/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.api;

import com.github.opensibyl.client.ApiException;
import com.github.opensibyl.client.model.Sibyl2FunctionContextSlim;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReferenceQueryApi
 */
@Disabled
public class ReferenceQueryApiTest {

    private final ReferenceQueryApi api = new ReferenceQueryApi();

    /**
     * funcctx query by ref
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncctxWithReferenceCountGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        Integer moreThan = null;
        Integer lessThan = null;
        List<Sibyl2FunctionContextSlim> response = api.apiV1FuncctxWithReferenceCountGet(repo, rev, moreThan, lessThan);
        // TODO: test validations
    }

    /**
     * funcctx query by referenced
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncctxWithReferencedCountGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        Integer moreThan = null;
        Integer lessThan = null;
        List<Sibyl2FunctionContextSlim> response = api.apiV1FuncctxWithReferencedCountGet(repo, rev, moreThan, lessThan);
        // TODO: test validations
    }

}
