/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.api;

import com.github.opensibyl.client.ApiException;
import com.github.opensibyl.client.model.ServiceRevStat;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for StatQueryApi
 */
@Disabled
public class StatQueryApiTest {

    private final com.github.opensibyl.client.api.StatQueryApi api = new StatQueryApi();

    /**
     * rev stat
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1RevStatGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        ServiceRevStat response = api.apiV1RevStatGet(repo, rev);
        // TODO: test validations
    }

}
