/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.api;

import com.github.opensibyl.client.ApiException;
import com.github.opensibyl.client.model.ObjectFunctionUploadUnit;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for UploadApi
 */
@Disabled
public class UploadApiTest {

    private final UploadApi api = new UploadApi();

    /**
     * upload functions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncPostTest() throws ApiException {
        ObjectFunctionUploadUnit payload = null;
        api.apiV1FuncPost(payload);
        // TODO: test validations
    }

}
