/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for CorePoint
 */
public class CorePointTest {
    private final CorePoint model = new CorePoint();

    /**
     * Model tests for CorePoint
     */
    @Test
    public void testCorePoint() {
        // TODO: test CorePoint
    }

    /**
     * Test the property 'column'
     */
    @Test
    public void columnTest() {
        // TODO: test column
    }

    /**
     * Test the property 'row'
     */
    @Test
    public void rowTest() {
        // TODO: test row
    }

}
