/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ExtractorValueUnit
 */
public class ExtractorValueUnitTest {
    private final ExtractorValueUnit model = new ExtractorValueUnit();

    /**
     * Model tests for ExtractorValueUnit
     */
    @Test
    public void testExtractorValueUnit() {
        // TODO: test ExtractorValueUnit
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
