/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ObjectClazzUploadUnit
 */
public class ObjectClazzUploadUnitTest {
    private final ObjectClazzUploadUnit model = new ObjectClazzUploadUnit();

    /**
     * Model tests for ObjectClazzUploadUnit
     */
    @Test
    public void testObjectClazzUploadUnit() {
        // TODO: test ObjectClazzUploadUnit
    }

    /**
     * Test the property 'clazzFileResult'
     */
    @Test
    public void clazzFileResultTest() {
        // TODO: test clazzFileResult
    }

    /**
     * Test the property 'workspace'
     */
    @Test
    public void workspaceTest() {
        // TODO: test workspace
    }

}
