/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ObjectFunctionContextUploadUnit
 */
public class ObjectFunctionContextUploadUnitTest {
    private final ObjectFunctionContextUploadUnit model = new ObjectFunctionContextUploadUnit();

    /**
     * Model tests for ObjectFunctionContextUploadUnit
     */
    @Test
    public void testObjectFunctionContextUploadUnit() {
        // TODO: test ObjectFunctionContextUploadUnit
    }

    /**
     * Test the property 'functionContext'
     */
    @Test
    public void functionContextTest() {
        // TODO: test functionContext
    }

    /**
     * Test the property 'workspace'
     */
    @Test
    public void workspaceTest() {
        // TODO: test workspace
    }

}
