/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ObjectWorkspaceConfig
 */
public class ObjectWorkspaceConfigTest {
    private final ObjectWorkspaceConfig model = new ObjectWorkspaceConfig();

    /**
     * Model tests for ObjectWorkspaceConfig
     */
    @Test
    public void testObjectWorkspaceConfig() {
        // TODO: test ObjectWorkspaceConfig
    }

    /**
     * Test the property 'repoId'
     */
    @Test
    public void repoIdTest() {
        // TODO: test repoId
    }

    /**
     * Test the property 'revHash'
     */
    @Test
    public void revHashTest() {
        // TODO: test revHash
    }

}
