/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ObjectRevInfo
 */
public class ObjectRevInfoTest {
    private final ObjectRevInfo model = new ObjectRevInfo();

    /**
     * Model tests for ObjectRevInfo
     */
    @Test
    public void testObjectRevInfo() {
        // TODO: test ObjectRevInfo
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'extras'
     */
    @Test
    public void extrasTest() {
        // TODO: test extras
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

}
