/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ObjectRevInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceRevStat
 */
public class ServiceRevStatTest {
    private final ServiceRevStat model = new ServiceRevStat();

    /**
     * Model tests for ServiceRevStat
     */
    @Test
    public void testServiceRevStat() {
        // TODO: test ServiceRevStat
    }

    /**
     * Test the property 'fileCount'
     */
    @Test
    public void fileCountTest() {
        // TODO: test fileCount
    }

    /**
     * Test the property 'functionCount'
     */
    @Test
    public void functionCountTest() {
        // TODO: test functionCount
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

}
