/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceTagUpload
 */
public class ServiceTagUploadTest {
    private final ServiceTagUpload model = new ServiceTagUpload();

    /**
     * Model tests for ServiceTagUpload
     */
    @Test
    public void testServiceTagUpload() {
        // TODO: test ServiceTagUpload
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'wc'
     */
    @Test
    public void wcTest() {
        // TODO: test wc
    }

}
