/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for Sibyl2FunctionWithTag
 */
public class Sibyl2FunctionWithTagTest {
    private final Sibyl2FunctionWithTag model = new Sibyl2FunctionWithTag();

    /**
     * Model tests for Sibyl2FunctionWithTag
     */
    @Test
    public void testSibyl2FunctionWithTag() {
        // TODO: test Sibyl2FunctionWithTag
    }

    /**
     * Test the property 'bodySpan'
     */
    @Test
    public void bodySpanTest() {
        // TODO: test bodySpan
    }

    /**
     * Test the property 'extras'
     */
    @Test
    public void extrasTest() {
        // TODO: test extras
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'receiver'
     */
    @Test
    public void receiverTest() {
        // TODO: test receiver
    }

    /**
     * Test the property 'returns'
     */
    @Test
    public void returnsTest() {
        // TODO: test returns
    }

    /**
     * Test the property 'span'
     */
    @Test
    public void spanTest() {
        // TODO: test span
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
