/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CoreSpan;
import org.openapitools.client.model.ExtractorValueUnit;
import org.openapitools.client.model.Sibyl2FunctionWithPath;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Sibyl2FunctionContext
 */
public class Sibyl2FunctionContextTest {
    private final Sibyl2FunctionContext model = new Sibyl2FunctionContext();

    /**
     * Model tests for Sibyl2FunctionContext
     */
    @Test
    public void testSibyl2FunctionContext() {
        // TODO: test Sibyl2FunctionContext
    }

    /**
     * Test the property 'bodySpan'
     */
    @Test
    public void bodySpanTest() {
        // TODO: test bodySpan
    }

    /**
     * Test the property 'calls'
     */
    @Test
    public void callsTest() {
        // TODO: test calls
    }

    /**
     * Test the property 'extras'
     */
    @Test
    public void extrasTest() {
        // TODO: test extras
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'receiver'
     */
    @Test
    public void receiverTest() {
        // TODO: test receiver
    }

    /**
     * Test the property 'returns'
     */
    @Test
    public void returnsTest() {
        // TODO: test returns
    }

    /**
     * Test the property 'reverseCalls'
     */
    @Test
    public void reverseCallsTest() {
        // TODO: test reverseCalls
    }

    /**
     * Test the property 'span'
     */
    @Test
    public void spanTest() {
        // TODO: test span
    }

}
