/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.opensibyl.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CoreSpan;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Sibyl2ClazzWithPath
 */
public class Sibyl2ClazzWithPathTest {
    private final Sibyl2ClazzWithPath model = new Sibyl2ClazzWithPath();

    /**
     * Model tests for Sibyl2ClazzWithPath
     */
    @Test
    public void testSibyl2ClazzWithPath() {
        // TODO: test Sibyl2ClazzWithPath
    }

    /**
     * Test the property 'extras'
     */
    @Test
    public void extrasTest() {
        // TODO: test extras
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'module'
     */
    @Test
    public void moduleTest() {
        // TODO: test module
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'span'
     */
    @Test
    public void spanTest() {
        // TODO: test span
    }

}
