/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ObjectFunctionWithSignature;
import org.openapitools.client.model.Sibyl2FunctionContext;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * file query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FileGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        List<String> response = api.apiV1FileGet(repo, rev);
        // TODO: test validations
    }

    /**
     * func query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String _file = null;
        String lines = null;
        List<ObjectFunctionWithSignature> response = api.apiV1FuncGet(repo, rev, _file, lines);
        // TODO: test validations
    }

    /**
     * func ctx query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncctxGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String _file = null;
        String lines = null;
        List<Sibyl2FunctionContext> response = api.apiV1FuncctxGet(repo, rev, _file, lines);
        // TODO: test validations
    }

    /**
     * upload status query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1MonitorUploadGetTest() throws ApiException {
        api.apiV1MonitorUploadGet();
        // TODO: test validations
    }

    /**
     * repo query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1RepoGetTest() throws ApiException {
        api.setCustomBaseUrl("http://127.0.0.1:9876");
        List<String> response = api.apiV1RepoGet();
        // TODO: test validations
    }

    /**
     * rev query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1RevGetTest() throws ApiException {
        String repo = null;
        List<String> response = api.apiV1RevGet(repo);
        // TODO: test validations
    }

    /**
     * ping example
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingGetTest() throws ApiException {
        api.pingGet();
        // TODO: test validations
    }

}
