/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Sibyl2ClazzWithPath;
import org.openapitools.client.model.Sibyl2FunctionContext;
import org.openapitools.client.model.Sibyl2FunctionWithPath;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExtrasApi
 */
@Disabled
public class ExtrasApiTest {

    private final ExtrasApi api = new ExtrasApi();

    /**
     * clazz diff query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ClazzDiffGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String diff = null;
        Map<String, List<Sibyl2ClazzWithPath>> response = api.apiV1ClazzDiffGet(repo, rev, diff);
        // TODO: test validations
    }

    /**
     * func diff query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncDiffGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String diff = null;
        Map<String, List<Sibyl2FunctionWithPath>> response = api.apiV1FuncDiffGet(repo, rev, diff);
        // TODO: test validations
    }

    /**
     * func ctx diff query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FuncctxDiffGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String diff = null;
        Map<String, List<Sibyl2FunctionContext>> response = api.apiV1FuncctxDiffGet(repo, rev, diff);
        // TODO: test validations
    }

}
