/*
 * openapi for sibyl2 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScopeApi
 */
@Disabled
public class ScopeApiTest {

    private final ScopeApi api = new ScopeApi();

    /**
     * file query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1FileGetTest() throws ApiException {
        String repo = null;
        String rev = null;
        String includeRegex = null;
        List<String> response = api.apiV1FileGet(repo, rev, includeRegex);
        // TODO: test validations
    }

    /**
     * repo query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1RepoGetTest() throws ApiException {
        List<String> response = api.apiV1RepoGet();
        // TODO: test validations
    }

    /**
     * rev query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1RevGetTest() throws ApiException {
        String repo = null;
        List<String> response = api.apiV1RevGet(repo);
        // TODO: test validations
    }

}
